CREATE TABLE PAIS(
    id_pais NUMBER GENERATED BY DEFAULT AS IDENTITY,
    pais VARCHAR2(100),
    PRIMARY KEY(id_pais)
);
CREATE TABLE REGION(
    id_region NUMBER GENERATED BY DEFAULT AS IDENTITY,
    region VARCHAR2(100),
    fk_id_pais NUMBER,
    FOREIGN KEY (fk_id_pais) REFERENCES pais (id_pais),
    PRIMARY KEY(id_region)
);
CREATE TABLE DEPTO(
    id_depto NUMBER GENERATED BY DEFAULT AS IDENTITY,
    depto VARCHAR2(100),
    fk_id_region NUMBER,
    FOREIGN KEY (fk_id_region) REFERENCES region (id_region),
    PRIMARY KEY(id_depto)
);
CREATE TABLE MUNICIPIO(
    id_municipio NUMBER GENERATED BY DEFAULT AS IDENTITY,
    municipio VARCHAR2(100),
    fk_id_depto NUMBER,
    FOREIGN KEY (fk_id_depto) REFERENCES depto (id_depto),
    PRIMARY KEY(id_municipio)
);




CREATE TABLE ELECCION(
    id_eleccion NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre_eleccion VARCHAR2(100),
    anio_eleccion VARCHAR2(100),
    PRIMARY KEY(id_eleccion)
);
CREATE TABLE PARTIDO(
    id_partido NUMBER GENERATED BY DEFAULT AS IDENTITY,
    partido VARCHAR2(100),
    nombre_partido VARCHAR2(100),
    PRIMARY KEY(id_partido)
);
CREATE TABLE RAZA(
    id_raza NUMBER GENERATED BY DEFAULT AS IDENTITY,
    raza VARCHAR2(100),
    PRIMARY KEY(id_raza)
);
CREATE TABLE SEXO(
    id_sexo NUMBER GENERATED BY DEFAULT AS IDENTITY,
    sexo VARCHAR2(100),
    PRIMARY KEY(id_sexo)
);


CREATE TABLE POBLACION(
    id_poblacion NUMBER GENERATED BY DEFAULT AS IDENTITY,
    primaria int,
    nivel_medio int,
    universitario int,
    analfabeto int,
    alfabeto int,
    fk_id_municipio NUMBER,
    fk_id_eleccion NUMBER,
    fk_id_partido NUMBER,
    FOREIGN KEY (fk_id_municipio) REFERENCES municipio (id_municipio),
    FOREIGN KEY (fk_id_eleccion) REFERENCES eleccion (id_eleccion),
    FOREIGN KEY (fk_id_partido) REFERENCES partido (id_partido),
    PRIMARY KEY(id_poblacion)  
);



CREATE TABLE PARTIDO_ELECCION (
    fk_id_partido NUMBER,
    fk_id_eleccion NUMBER,
    descripcion VARCHAR2(100),
    puesto VARCHAR2(100),
    FOREIGN KEY (fk_id_partido) REFERENCES partido (id_partido),
    FOREIGN KEY (fk_id_eleccion) REFERENCES eleccion (id_eleccion),
    PRIMARY KEY(fk_id_partido,fk_id_eleccion)  
);






CREATE TABLE DETALLE_ELECCION(
    fk_id_municipio NUMBER,
    fk_id_eleccion NUMBER,
    descripcion_detalle VARCHAR2(100) default 'Descripcion', 
    FOREIGN KEY (fk_id_municipio) REFERENCES municipio(id_municipio),
    FOREIGN KEY (fk_id_eleccion) REFERENCES eleccion(id_eleccion),
    PRIMARY KEY(fk_id_municipio,fk_id_eleccion)  
);
CREATE TABLE DETALLE_PARTIDO(
    fk_id_municipio NUMBER,
    fk_id_partido NUMBER,
    descripcion_detalle VARCHAR2(100) default 'Descripcion', 
    FOREIGN KEY (fk_id_municipio) REFERENCES municipio(id_municipio),
    FOREIGN KEY (fk_id_partido) REFERENCES partido(id_partido),
    PRIMARY KEY(fk_id_municipio,fk_id_partido)  
);
CREATE TABLE DETALLE_RAZA(
    fk_id_poblacion NUMBER,
    fk_id_raza NUMBER,
    descripcion_detalle VARCHAR2(100) default 'Descripcion', 
    FOREIGN KEY (fk_id_poblacion) REFERENCES poblacion(id_poblacion),
    FOREIGN KEY (fk_id_raza) REFERENCES raza(id_raza),
    PRIMARY KEY(fk_id_poblacion,fk_id_raza)  
);
CREATE TABLE DETALLE_SEXO(
    fk_id_poblacion NUMBER,
    fk_id_sexo NUMBER,
    descripcion_detalle VARCHAR2(100) default 'Descripcion', 
    FOREIGN KEY (fk_id_poblacion) REFERENCES poblacion(id_poblacion),
    FOREIGN KEY (fk_id_sexo) REFERENCES sexo(id_sexo),
    PRIMARY KEY(fk_id_poblacion,fk_id_sexo)  
);
